### ISSUE TITLE
Glavni program, uvoz, zemljevid

### ISSUE THREAD

**Issue by jaanos** [nejapletikos/APPR-2014-15#3]
V glavnem programu imaš še vedno zakomentiran klic programa `vizualizacija.r` - sedaj ga seveda odkomentiraj.

Podatki iz datoteke `nesreceurejeno.csv` se ti uvozijo kot nizi, ker uvoziš tudi vrstico z glavo tabele (ki jo sicer potem pobrišeš). Da se tega znebiš in se ti pravilno uvozijo številke, funkciji `read.table` dodaj parameter `header = TRUE`; potem ne bo potrebno brisati prve vrstice.

Če poženem `vizualizacija.r`, se ustavi, ker nikjer nimaš definirane spremenljivke `regije` (tista iz `zemljevid.r` najbrž ni prava - sicer pa imaš tam več ali manj le skopirano kodo iz `uvozi.zemljevid.r`, tako da te datoteke ne potrebuješ). Namesto nje želiš najbrž uporabiti razpredelnico `nesrece`.

Poleg tega ti manjka tudi spremenljivka `norm.povprecje`, ki jo moraš seveda izračunati (smiselno bi jo bilo tudi preimenovati). Narediš lahko nekaj takega:

``` R
min.nesrece <- min(rregije[,1], na.rm=TRUE)
max.nesrece <- max(rregije[,1], na.rm=TRUE)
norm.nesrece <- (rregije[,1]-min.nesrece)/(max.nesrece-min.nesrece)

n <- 100
barve <- rgb(1, 1, (n:1)/n)
plot(slo, col = barve[unlist(1+(n-1)*norm.nesrece)], bg="lightblue")
```

Na zemljevid bi koristilo dodati legendo, ki bo povedala, za kakšne številke gre. Sedaj imaš v spremenljivki `barve` barvno lestvico, ki jo lahko uporabiš za risanje legende:

``` R
k <- 5 # število vnosov v legendi
lestvica <- seq(min.nesrece, max.nesrece, (max.nesrece-min.nesrece)/(k-1))
legend("bottomright", legend = round(lestvica),
       fill = barve[seq(1, n, (n-1)/(k-1))], bg = "white")
```

Ne pozabi še dodati zemljevida v poročilo. Pred obstoječima grafoma dodaj prazno vrstico, da ne bosta segala čez rob strani.

**Comment by jaanos** [comment]
Glede na to, da imaš v sredo predstavitev, te prosim, da **do jutri** poskrbiš, da bo na GitHub naložena delujoča različica tvojega programa in poročila. Da preizkusiš, ali ti program deluje, najprej poženi `clearpdf.r`, nato pa še `projekt.r`. Slednji se mora končati brez napake in izrisati vse želene slike. Po tem se bo moralo tudi poročilo dati prevesti.

**Comment by nejapletikos** [comment]
Pozdravljeni.
Zanima me, če imate jutri mogoče čas saj bi rabila pomoč pri svojem
programu.
Lep pozdrav,
Neja Pletikos
Dne 18. jan. 2015 21:12 je oseba "Janoš Vidali" notifications@github.com
napisala:

**Comment by jaanos** [comment]
Lahko pogledava jutri po vajah.
